// AUTO-GENERATED by server/src/codegen.py — do not edit by hand

export type SessionStatus = "created" | "active" | "paused" | "closed";

export type AudioSource = "webrtc" | "crosstalk";

export type StageKind = "listen" | "translate" | "speak" | "prosody";

export interface OutputStreamInfo {
  name: string;
  kind: string;
  label: string;
}

export interface PipelineInfo {
  id: string;
  name: string;
  description: string;
  output_streams: OutputStreamInfo[];
}

export interface StageInfo {
  id: string;
  kind: StageKind;
  name: string;
  description: string;
  requires_gpu: boolean;
  default_for_kind: boolean;
}

export interface StageSelection {
  listen: string;
  translate: string;
  speak: string;
  prosody: string | null;
}

export interface SessionCreate {
  pipeline_id: string;
  sample_rate?: number;
  channels?: number;
  label?: string;
  audio_context_seconds?: number;
  audio_source?: AudioSource;
  crosstalk_session_id?: string | null;
  stages?: StageSelection | null;
}

export interface SessionUpdate {
  label?: string | null;
  status?: SessionStatus | null;
}

export interface SessionStats {
  bytes_received: number;
  bytes_sent: number;
  chunks_received: number;
  chunks_sent: number;
  duration_seconds: number;
  pipeline_latency_ms: number;
  audio_delay_seconds: number;
}

export interface Session {
  id: string;
  pipeline_id: string;
  label: string;
  status: SessionStatus;
  sample_rate: number;
  channels: number;
  audio_context_seconds: number;
  audio_source: AudioSource;
  crosstalk_session_id: string | null;
  stages: StageSelection | null;
  created_at: number;
  stats: SessionStats;
}

export interface ServerStats {
  uptime_seconds: number;
  active_sessions: number;
  total_sessions: number;
  total_bytes_processed: number;
  available_pipelines: number;
}

export interface CrosstalkSessionInfo {
  id: string;
  name: string;
  description: string;
}

export interface CrosstalkChannelInfo {
  id: string;
  name: string;
  type: string;
  session_id: string;
}

export type MetadataKind = "prosody" | "instructions";

export interface ProsodyFrame {
  f0_hz: number | null;
  pitch_confidence: number | null;
  energy: number | null;
  speaking_rate: number | null;
  is_pause: boolean | null;
  boundary: string | null;
  emphasis: number | null;
  confidence: number | null;
  features: Record<string, number>;
}

export interface SynthesisInstructions {
  hints: Record<string, unknown>;
  markers: Record<string, unknown>[];
}

export interface MetadataEnvelope {
  schema_version: number;
  stream: string;
  kind: MetadataKind;
  sequence: number;
  source_utterance_id: string | null;
  target_utterance_id: string | null;
  start_ms: number | null;
  end_ms: number | null;
  prosody: ProsodyFrame | null;
  instructions: SynthesisInstructions | null;
  payload: Record<string, unknown>;
}
