// AUTO-GENERATED by server/src/codegen.py — do not edit by hand

export type SessionStatus = "created" | "active" | "paused" | "closed";

export interface OutputStreamInfo {
  name: string;
  kind: string;
  label: string;
}

export interface PipelineInfo {
  id: string;
  name: string;
  description: string;
  output_streams: OutputStreamInfo[];
}

export interface SessionCreate {
  pipeline_id: string;
  sample_rate?: number;
  channels?: number;
  label?: string;
  audio_context_seconds?: number;
}

export interface SessionUpdate {
  label?: string | null;
  status?: SessionStatus | null;
}

export interface SessionStats {
  bytes_received: number;
  bytes_sent: number;
  chunks_received: number;
  chunks_sent: number;
  duration_seconds: number;
  pipeline_latency_ms: number;
}

export interface Session {
  id: string;
  pipeline_id: string;
  label: string;
  status: SessionStatus;
  sample_rate: number;
  channels: number;
  audio_context_seconds: number;
  created_at: number;
  stats: SessionStats;
}

export interface ServerStats {
  uptime_seconds: number;
  active_sessions: number;
  total_sessions: number;
  total_bytes_processed: number;
  available_pipelines: number;
}
