"""Export shared Pydantic models as JSON Schema, then generate TypeScript types.

Usage:
    uv run python -m src.codegen          # writes ../client/src/api/types.gen.ts
    uv run python -m src.codegen --check  # exits non-zero if generated file is stale
"""

from __future__ import annotations

import enum
import sys
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from src.models import (
    PipelineInfo,
    ServerStats,
    Session,
    SessionCreate,
    SessionStats,
    SessionStatus,
    SessionUpdate,
)

SHARED_MODELS: list[type] = [
    SessionStatus,
    PipelineInfo,
    SessionCreate,
    SessionUpdate,
    SessionStats,
    Session,
    ServerStats,
]

REQUEST_MODELS: set[str] = {"SessionCreate", "SessionUpdate"}

OUT_PATH = Path(__file__).resolve().parent.parent.parent / "client" / "src" / "api" / "types.gen.ts"

JSON_TO_TS: dict[str, str] = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _resolve_ref(ref: str, defs: dict[str, Any]) -> dict[str, Any]:
    name = ref.rsplit("/", 1)[-1]
    return defs[name]


def _ts_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return name

    if "enum" in schema:
        return " | ".join(f'"{v}"' for v in schema["enum"])

    if "anyOf" in schema:
        parts: list[str] = []
        for variant in schema["anyOf"]:
            parts.append(_ts_type(variant, defs))
        return " | ".join(parts)

    if "allOf" in schema:
        return _ts_type(schema["allOf"][0], defs)

    json_type = schema.get("type", "string")
    if json_type == "array":
        items = schema.get("items", {"type": "string"})
        return f"{_ts_type(items, defs)}[]"

    return JSON_TO_TS.get(json_type, "unknown")


def _is_required(prop_name: str, schema: dict[str, Any], model_name: str) -> bool:
    if model_name not in REQUEST_MODELS:
        return True
    required_list = schema.get("required", [])
    if prop_name in required_list:
        return "default" not in schema.get("properties", {}).get(prop_name, {})
    return False


def _generate_interface(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    props = schema.get("properties", {})
    if not props:
        return ""
    lines = [f"export interface {name} {{"]
    for prop_name, prop_schema in props.items():
        ts = _ts_type(prop_schema, defs)
        optional = "" if _is_required(prop_name, schema, name) else "?"
        lines.append(f"  {prop_name}{optional}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def _generate_enum(name: str, schema: dict[str, Any]) -> str:
    values = schema.get("enum", [])
    if not values:
        return ""
    union = " | ".join(f'"{v}"' for v in values)
    return f"export type {name} = {union};"


def generate_typescript() -> str:
    defs: dict[str, Any] = {}
    model_schemas: list[tuple[str, dict[str, Any]]] = []

    for model in SHARED_MODELS:
        if isinstance(model, type) and issubclass(model, enum.Enum):
            values = [e.value for e in model]
            schema = {"enum": values, "type": "string"}
            name = model.__name__
        else:
            adapter = TypeAdapter(model)
            schema = adapter.json_schema(ref_template="#/$defs/{model}", mode="serialization")
            name = model.__name__
            if "$defs" in schema:
                defs.update(schema.pop("$defs"))

        model_schemas.append((name, schema))
        defs[name] = schema

    blocks: list[str] = []
    emitted: set[str] = set()

    for name, schema in model_schemas:
        if name in emitted:
            continue
        emitted.add(name)

        if "enum" in schema and "properties" not in schema:
            blocks.append(_generate_enum(name, schema))
        elif "properties" in schema:
            blocks.append(_generate_interface(name, schema, defs))

    return (
        "// AUTO-GENERATED by server/src/codegen.py — do not edit by hand\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def main() -> None:
    content = generate_typescript()
    check = "--check" in sys.argv

    if check:
        if not OUT_PATH.exists():
            print(f"MISSING: {OUT_PATH}")
            sys.exit(1)
        existing = OUT_PATH.read_text()
        if existing != content:
            print(f"STALE: {OUT_PATH}")
            sys.exit(1)
        print("OK: types are up to date")
        return

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
